// Token naming convention: evolutions/EVO-002_design-token-refactoring/token-convention.md
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  safelist: [
    'wave5-panel',
    'wave5-input',
    'wave5-pill',
    'wave5-object',
    'wave5-object--bike',
    'wave5-object--cassette',
    'wave5-object--hub',
    'wave5-object--rotor',
    'wave5-object--wheel',
  ],
  theme: {
    extend: {
      colors: {
        paper: {
          0: 'var(--paper-0)',
          1: 'var(--paper-1)',
          2: 'var(--paper-2)',
          3: 'var(--paper-3)',
        },
        ink: {
          1:  'var(--ink-1)',
          2:  'var(--ink-2)',
          3:  'var(--ink-3)',
          4:  'var(--ink-4)',
          5:  'var(--ink-5)',
          6:  'var(--ink-6)',
          7:  'var(--ink-7)',
          8:  'var(--ink-8)',
          9:  'var(--ink-9)',
          10: 'var(--ink-10)',
          11: 'var(--ink-11)',
          12: 'var(--ink-12)',
        },
        brass: {
          1:  'var(--brass-1)',
          2:  'var(--brass-2)',
          3:  'var(--brass-3)',
          4:  'var(--brass-4)',
          5:  'var(--brass-5)',
          6:  'var(--brass-6)',
          7:  'var(--brass-7)',
          8:  'var(--brass-8)',
          9:  'var(--brass-9)',
          10: 'var(--brass-10)',
          11: 'var(--brass-11)',
          12: 'var(--brass-12)',
        },
        sage: {
          1:  'var(--sage-1)',
          2:  'var(--sage-2)',
          3:  'var(--sage-3)',
          4:  'var(--sage-4)',
          5:  'var(--sage-5)',
          6:  'var(--sage-6)',
          7:  'var(--sage-7)',
          8:  'var(--sage-8)',
          9:  'var(--sage-9)',
          10: 'var(--sage-10)',
          11: 'var(--sage-11)',
          12: 'var(--sage-12)',
        },
        signal: {
          up:   'var(--signal-up)',
          down: 'var(--signal-down)',
          warn: 'var(--signal-warn)',
          info: 'var(--signal-info)',
        },
        // Semantic color tokens — bg-*, text-*, border-* utilities
        bg: {
          page:     'var(--bg-page)',
          elevated: 'var(--bg-elevated)',
          recessed: 'var(--bg-recessed)',
          inverse:  'var(--bg-inverse)',
        },
        fg: {
          primary:    'var(--fg-primary)',
          secondary:  'var(--fg-secondary)',
          muted:      'var(--fg-muted)',
          faint:      'var(--fg-faint)',
          inverse:    'var(--fg-inverse)',
          accent:     'var(--fg-accent)',
          link:       'var(--fg-link)',
          'link-hover': 'var(--fg-link-hover)',
        },
        rule: {
          strong:  'var(--rule-strong)',
          default: 'var(--rule-default)',
          faint:   'var(--rule-faint)',
        },
        border: {
          default: 'var(--border-default)',
          strong:  'var(--border-strong)',
          focus:   'var(--border-focus)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          'fg-on': 'var(--accent-fg-on)',
        },
      },
      fontFamily: {
        display: ['var(--font-display)', 'sans-serif'],
        sans:    ['var(--font-sans)',    'sans-serif'],
        mono:    ['var(--font-mono)',    'monospace'],
      },
      fontSize: {
        // ds- prefix to avoid overriding Tailwind built-in font size scale
        'ds-2xs':  'var(--text-2xs)',
        'ds-xs':   'var(--text-xs)',
        'ds-sm':   'var(--text-sm)',
        'ds-base': 'var(--text-base)',
        'ds-md':   'var(--text-md)',
        'ds-lg':   'var(--text-lg)',
        'ds-xl':   'var(--text-xl)',
        'ds-2xl':  'var(--text-2xl)',
        'ds-3xl':  'var(--text-3xl)',
        'ds-4xl':  'var(--text-4xl)',
        'ds-5xl':  'var(--text-5xl)',
        'ds-6xl':  'var(--text-6xl)',
      },
      lineHeight: {
        'tight':       'var(--leading-tight)',
        'snug':        'var(--leading-snug)',
        'normal-ds':   'var(--leading-normal)',
        'relaxed-ds':  'var(--leading-relaxed)',
      },
      letterSpacing: {
        widest:      '0.18em',
        'tighter-ds': 'var(--tracking-tighter)',
        'tight-ds':   'var(--tracking-tight)',
        'normal-ds':  'var(--tracking-normal)',
        'wide-ds':    'var(--tracking-wide)',
      },
      fontWeight: {
        light:    'var(--weight-light)',
        regular:  'var(--weight-regular)',
        medium:   'var(--weight-medium)',
        semibold: 'var(--weight-semibold)',
        bold:     'var(--weight-bold)',
        black:    'var(--weight-black)',
      },
      opacity: {
        '88': '0.88',
        '40': '0.4',
      },
      spacing: {
        // ds- prefix to avoid overriding Tailwind built-in spacing scale
        'ds-0':  'var(--space-0)',
        'ds-px': 'var(--space-px)',
        'ds-1':  'var(--space-1)',
        'ds-2':  'var(--space-2)',
        'ds-3':  'var(--space-3)',
        'ds-4':  'var(--space-4)',
        'ds-5':  'var(--space-5)',
        'ds-6':  'var(--space-6)',
        'ds-8':  'var(--space-8)',
        'ds-10': 'var(--space-10)',
        'ds-12': 'var(--space-12)',
        'ds-16': 'var(--space-16)',
        'ds-20': 'var(--space-20)',
        'ds-24': 'var(--space-24)',
        'ds-32': 'var(--space-32)',
      },
      borderRadius: {
        xs:   'var(--radius-xs)',
        none: 'var(--radius-none)',
        sm:   'var(--radius-sm)',
        panel: 'var(--radius-panel)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        menu:      'var(--shadow-menu)',
        surface:   'var(--shadow-surface)',
        raised:    'var(--shadow-raised)',
        none:      'var(--shadow-none)',
        hairline:  'var(--shadow-hairline)',
        keyline:   'var(--shadow-keyline)',
        focus:     'var(--shadow-focus)',
      },
      transitionDuration: {
        'instant': 'var(--duration-instant)',
        'quick':   'var(--duration-quick)',
        'base-ds': 'var(--duration-base)',
        'slow':    'var(--duration-slow)',
      },
      transitionTimingFunction: {
        'standard':   'var(--ease-standard)',
        'emphasized': 'var(--ease-emphasized)',
      },
      maxWidth: {
        'page':   'var(--container-page)',
        'narrow': 'var(--container-narrow)',
      },
    },
  },
  plugins: [],
}
