/* Sample dataset — copied from frontend/src/data/wheelsData.js (codebase source of truth).
   In production this comes from a backend; here it's static for the prototype. */

window.WHEELS = [
  { id: 1,  brand: 'Roval',       model: 'Alpinist CLX II',         weight: 1225, diameter: 700, rim: { material: 'Carbon', hookless: false, depth: 33,   width: 25.5 }, spokes: { brand: 'Sapim',          model: 'CX-Ray',           material: 'Stainless Steel' }, hub: { brand: 'DT Swiss',         model: '240' },         prices: [1299, 1349] },
  { id: 2,  brand: 'Zipp',        model: '303 Firecrest',           weight: 1510, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 45,   width: 30   }, spokes: { brand: 'Sapim',          model: 'CX-Sprint',        material: 'Stainless Steel' }, hub: { brand: 'Zipp',             model: 'ZR1' },         prices: [1750] },
  { id: 3,  brand: 'DT Swiss',    model: 'ARC 1100 Dicut 62',       weight: 1510, diameter: 700, rim: { material: 'Carbon', hookless: false, depth: 62,   width: 27   }, spokes: { brand: 'DT Swiss',       model: 'Aerolite',         material: 'Stainless Steel' }, hub: { brand: 'DT Swiss',         model: '180' },         prices: [1990, 2050] },
  { id: 4,  brand: 'Fulcrum',     model: 'Racing Zero Carbon',      weight: 1390, diameter: 700, rim: { material: 'Carbon', hookless: false, depth: 40,   width: 26   }, spokes: { brand: 'Fulcrum',        model: 'Aero Bladed',      material: 'Aluminum'        }, hub: { brand: 'Fulcrum',          model: 'USB Ceramic' }, prices: [1200] },
  { id: 5,  brand: 'Shimano',     model: 'Dura-Ace WH-R9270 C50',   weight: 1492, diameter: 700, rim: { material: 'Carbon', hookless: false, depth: 50,   width: 28   }, spokes: { brand: 'Shimano',        model: 'Bladed',           material: 'Stainless Steel' }, hub: { brand: 'Shimano',          model: 'Dura-Ace' },    prices: [1600, 1690] },
  { id: 6,  brand: 'Hunt',        model: '60 Limitless',            weight: 1620, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 60,   width: 34   }, spokes: { brand: 'Pillar',         model: 'Wing 20',          material: 'Stainless Steel' }, hub: { brand: 'Hunt',             model: 'SPRINT' },      prices: [899] },
  { id: 7,  brand: 'Campagnolo',  model: 'Bora Ultra WTO 45',       weight: 1349, diameter: 700, rim: { material: 'Carbon', hookless: false, depth: 45,   width: 26   }, spokes: { brand: 'Campagnolo',     model: 'Aero',             material: 'Stainless Steel' }, hub: { brand: 'Campagnolo',       model: 'Bora Ultra' },  prices: [2200] },
  { id: 8,  brand: 'Mavic',       model: 'Cosmic Pro Carbon SL',    weight: 1610, diameter: 700, rim: { material: 'Carbon', hookless: false, depth: 40,   width: 25   }, spokes: { brand: 'Mavic',          model: 'Bladed',           material: 'Stainless Steel' }, hub: { brand: 'Mavic',            model: 'Instant Drive 360' }, prices: [1099] },
  { id: 9,  brand: 'Bontrager',   model: 'Aeolus RSL 37',           weight: 1314, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 37,   width: 28   }, spokes: { brand: 'DT Swiss',       model: 'Aerolite',         material: 'Stainless Steel' }, hub: { brand: 'DT Swiss',         model: '240 EXP' },     prices: [2000, 2100] },
  { id: 10, brand: 'Giant',       model: 'SLR 0 36',                weight: 1375, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 36,   width: 28   }, spokes: { brand: 'DT Swiss',       model: 'Aero',             material: 'Stainless Steel' }, hub: { brand: 'CADEX',            model: 'R36' },         prices: [1800] },
  { id: 11, brand: 'Enve',        model: 'SES 4.5 AR',              weight: 1470, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 45,   width: 32   }, spokes: { brand: 'Sapim',          model: 'CX-Ray',           material: 'Stainless Steel' }, hub: { brand: 'Enve',             model: 'Alloy Centerlock' }, prices: [2800] },
  { id: 12, brand: 'Vittoria',    model: 'Elusion 45',              weight: 1580, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 45,   width: 26   }, spokes: { brand: 'Pillar',         model: 'Bladed',           material: 'Stainless Steel' }, hub: { brand: 'Vittoria',         model: 'Elusion' },     prices: [750] },
  { id: 13, brand: 'Reynolds',    model: 'AR 58',                   weight: 1520, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 58,   width: 28   }, spokes: { brand: 'Sapim',          model: 'CX-Ray',           material: 'Stainless Steel' }, hub: { brand: 'Industry Nine',    model: 'I9' },          prices: [1650] },
  { id: 14, brand: 'Boyd',        model: 'Altamont 60',             weight: 1620, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 60,   width: 28   }, spokes: { brand: 'Sapim',          model: 'CX-Ray',           material: 'Stainless Steel' }, hub: { brand: 'Boyd',             model: 'Altamont' },    prices: [850] },
  { id: 15, brand: 'Princeton',   model: 'CarbonWorks GRIT 4540',   weight: 1480, diameter: 700, rim: { material: 'Carbon', hookless: true,  depth: 45,   width: 30   }, spokes: { brand: 'Sapim',          model: 'CX-Ray',           material: 'Stainless Steel' }, hub: { brand: 'White Industries', model: 'CLD' },         prices: [2300] },
];

window.minPrice = (w) => Math.min(...w.prices);
